### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by jangalinski** [holixon/avro-registry-adapter#14]
let's go public

**Comment by zambrovski** [comment]
Hi,

I shaved the `pom.xml` fixed issues with plugins and wrong Kotlin version and tuned-up the GH actions.
Please review the changes.

Cheers,

S.

**Comment by jangalinski** [comment]
seems like the major change to the poms is


```
  <properties>
    <jacoco.skip>false</jacoco.skip>
  </properties>
```

wouldn't it be better to change the default and enable skip where required?

**Comment by jangalinski** [comment]
what is the purpose of the `coverage-aggregate`?

**Comment by jangalinski** [comment]
else: fine

**Comment by zambrovski** [comment]
should we try to release?

**Comment by jangalinski** [comment]
Trying is the first step to failure

go for it!
