### ISSUE TITLE
provide osgi plugin for apicurio registry adapter

### ISSUE THREAD

**Issue by jangalinski** [holixon/avro-registry-adapter#58]
One of the main goals of this project is to provide a base framework for avro serialization with axonframework.
To use avro from the axon server dashboard, this requires an osgi plugin to be installed on the axon server.

While the concrete axon specific listeners plugin is part of holixon/axon-avro-serializer, the core functionality (configuring and accessing an apicurio registry) should be part of this repo.

This way, we can later just exchange the core plugin (for example to use confluent registry) without providing multiple implementations for axon server.

So the task is: Parallel to the apicurio rest client module, provide an osgi bundle that allows running a registry-adapter as a plugin.

**Comment by zambrovski** [comment]
will be fixed in https://github.com/holixon/axon-avro-serializer/issues/96
